CPP=g++

all:
	$(CPP) src/AdvancedMonteCarlo.cpp -o AdvancedMonteCarlo; $(CPP) src/MonteCarloAndExoticOptions.cpp -o MonteCarloAndExoticOptions

clean:
	rm -f AdvancedMonteCarlo MonteCarloAndExoticOptions

